name: test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: moguri/setup-blender@v1
        with:
          blender-version: "4.5"

      - run: blender --version

      - name: Checkout Addon
        uses: actions/checkout@v4
        with:
          path: CAD_Sketcher

      - name: Validate Extension
        run: blender --background --command extension validate
        working-directory: ./CAD_Sketcher

      - name: Build Extension
        run: blender --background --command extension build --output-filepath ./CAD_Sketcher.zip
        working-directory: ./CAD_Sketcher

      - name: Install Extension
        run: blender --background --command extension install-file --repo user_default --enable ./CAD_Sketcher.zip
        working-directory: ./CAD_Sketcher

      - name: Run Tests
        run: blender --background --addons CAD_Sketcher --python-expr "import bpy; bpy.context.preferences.view.show_splash=False; bpy.ops.view3d.slvs_test()"
        working-directory: ./CAD_Sketcher
